List<Map> NavList = [
  {
    "title":"酒店",
    "pic_src":"http://s.qunarzz.com/homenode/images/touchheader/hotel.png"
  },
  {
    "title":"机票",
    "pic_src":"http://s.qunarzz.com/homenode/images/touchheader/flight.png"
  },
  {
    "title":"去哪玩",
    "pic_src":"http://s.qunarzz.com/homenode/images/touchheader/package.png"
  },
  {
    "title":"拼车",
    "pic_src":"http://s.qunarzz.com/homenode/images/touchheader/train.png"
  },
  {
    "title":"拼团旅行",
    "pic_src":"http://s.qunarzz.com/homenode/images/touchheader/piao.png"
  }
];